version: '3'

services:
  frontend:
    image: ghcr.io/dliebg/schwering_app_solar/frontend:main
    container_name: schwering_app_solar_frontend
    restart: unless-stopped
    ports:
      - 10005:80
    labels:
      - "com.centurylinklabs.watchtower.scope=schwering_app_solar"

  backend:
    image: ghcr.io/dliebg/schwering_app_solar/backend:main
    container_name: schwering_app_solar_backend
    restart: unless-stopped
    env_file: .env
    labels:
      - "com.centurylinklabs.watchtower.scope=schwering_app_solar"

  watchtower:
    image: containrrr/watchtower
    container_name: schwering_app_solar_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: schwering_app_solar_frontend schwering_app_solar_frontend -i 3600 --scope schwering_app_solar
    labels:
      - "com.centurylinklabs.watchtower.scope=schwering_app_solar"
