version: '3'

services:
  frontend:
    # build: frontend
    image: ghcr.io/dliebg/schwering_app_solar/frontend:main
    container_name: schwering_app_solar_frontend
    restart: unless-stopped
    ports:
      - 10005:80

  backend:
    # build: backend
    image: ghcr.io/dliebg/schwering_app_solar/backend:main
    container_name: schwering_app_solar_backend
    restart: unless-stopped
    env_file: .env

  watchtower:
    image: containrrr/watchtower
    container_name: schwering_app_solar_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: schwering_app_solar_frontend schwering_app_solar_frontend -i 3600
